In [3]:
input_1 = [[11,12,13,14],
           [21,22,23,24],
           [31,32,33,34]]

import numpy as np
array_2d = np.array(input_1)
array_2d

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

# First column of the input array, first row of the input array, last column of the input array, last row of the input array respectively.

In [17]:
col_first = array_2d[ : ,0]
row_first = array_2d[0]
col_last =  array_2d[ : ,-1]
row_last =  array_2d[-1]
print(col_first)
print(row_first)
print(col_last)
print(row_last)


[11 21 31]
[11 12 13 14]
[14 24 34]
[31 32 33 34]


In [15]:
import pandas as pd

In [19]:
marks = pd.read_csv(r"C:\Users\Yoga\Downloads\class-grades.csv")

In [21]:
marks.info

<bound method DataFrame.info of     Prefix  Assignment  Tutorial  Midterm  TakeHome  Final
0        5       57.14     34.09    64.38     51.48  52.50
1        8       95.05    105.49    67.50     99.07  68.33
2        8       83.70     83.17    30.00     63.15  48.89
3        7       81.22     96.06    49.38    105.93  80.56
4        8       91.32     93.64    95.00    107.41  73.89
..     ...         ...       ...      ...       ...    ...
94       8       96.73    103.71    45.00     93.52  61.94
95       7       85.34     80.54    41.25     93.70  39.72
96       8       89.94    102.77    87.50     90.74  87.78
97       7       95.60     76.13    66.25     99.81  85.56
98       8       63.40     97.37    73.12     72.78  77.22

[99 rows x 6 columns]>

In [22]:
marks.dropna(axis=0,thresh=5)

Prefix  Assignment  Tutorial  Midterm  TakeHome  Final
0        5       57.14     34.09    64.38     51.48  52.50
1        8       95.05    105.49    67.50     99.07  68.33
2        8       83.70     83.17    30.00     63.15  48.89
3        7       81.22     96.06    49.38    105.93  80.56
4        8       91.32     93.64    95.00    107.41  73.89
..     ...         ...       ...      ...       ...    ...
94       8       96.73    103.71    45.00     93.52  61.94
95       7       85.34     80.54    41.25     93.70  39.72
96       8       89.94    102.77    87.50     90.74  87.78
97       7       95.60     76.13    66.25     99.81  85.56
98       8       63.40     97.37    73.12     72.78  77.22

[87 rows x 6 columns]

In [24]:
marks.isnull().sum(axis=0)

Prefix         0
Assignment     2
Tutorial      12
Midterm       16
TakeHome       9
Final          5
dtype: int64